Add `template` function
hiphops-io/hiphops-io.github.io pull request #20
Opened 2023-12-20 18:26 UTC by lukaso

https://trello.com/c/LIa6zLZC/1110-add-template-dsl-function

2023-12-20 18:27 UTC, lukaso commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add template() DSL function](https://trello.com/c/LIa6zLZC/1110-add-template-dsl-function)

2023-12-20 19:07 UTC, manterfield requested changes

2023-12-20 19:07 UTC, manterfield commented on docs/hops-functions.md
> +The `template` function accepts a filename and variables. The template will be loaded from the filename and then populated with the variables. The content is returned as a string.
Could do with mentioning that it renders the template, rather than populated with variables. This makes it sound like a straight string replace, but much of the logic in templating is outside of that.

2023-12-20 19:07 UTC, manterfield commented on docs/hops-functions.md
> +template("template.tmpl", { "accountId": "anaccount", "password": "asecret" })
When using dummy names in examples, try to avoid things that could potentially be interpreted by a new user as being a special value. Here `"template.tmpl"` doesn't implicitly tell me much and could leave a user wondering if it _must_ be that value, or that it must end in `.tmpl`. We can avoid that ambiguity with good choices.

I'd go for something like `"mytemplate.html"` or similar, then make sure the below example marries up to the name.

2023-12-20 19:07 UTC, manterfield commented on docs/hops-functions.md
> +> Note: Unlike Django, HTML escaping is disabled by default. To enable it, see below.
We don't tell them what HTML escaping actually means. A few words would be good

> HTML escaping (where html is blah blah) is disabled by default.

2023-12-20 19:07 UTC, manterfield commented on docs/hops-functions.md
> +The file is found in the directory of the `.hops` file (same as the `file` function).
Also, try to avoid using `.hops` to refer to `something.hops` files. We've got the default `~/.hops` dir and this could cause confusion.

I've started trying to either use `*.hops` or `example.hops` and so on.

2023-12-21 09:46 UTC, lukaso commented on docs/hops-functions.md
> +The file is found in the directory of the `.hops` file (same as the `file` function).
Done

2023-12-21 09:46 UTC, lukaso commented on docs/hops-functions.md
> +The `template` function accepts a filename and variables. The template will be loaded from the filename and then populated with the variables. The content is returned as a string.
Done

2023-12-21 09:55 UTC, lukaso commented on docs/hops-functions.md
> +> Note: Unlike Django, HTML escaping is disabled by default. To enable it, see below.
Done.

2023-12-21 09:58 UTC, merged